CREATE TABLE chat
(
    id         BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    tg_chat_id BIGINT NOT NULL
);

CREATE TABLE player_info_to_chat
(
    id        BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    player_id BIGINT NOT NULL,
    chat_id   BIGINT NOT NULL,
    FOREIGN KEY (player_id) REFERENCES player_info (id) ON DELETE CASCADE,
    FOREIGN KEY (chat_id) REFERENCES chat (id) ON DELETE CASCADE
);

